import type { Metadata } from 'next'
import {Bebas_Neue, Oswald} from 'next/font/google'
import './globals.css'
import Providers from "@/utils/Providers";

const Bebas = Bebas_Neue({
    subsets: ['latin'] ,
    weight: '400',
    display: 'swap',
    preload: true,
    variable: '--font-bebas',
})
const oswald=Oswald({
    weight: '200',
    display: 'swap',
    subsets: ['latin'],
    preload: true,
    variable: '--font-oswald',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${Bebas.variable} ${oswald.variable}`}>
      <body >
      <Providers >
      {children}
      </Providers></body>
    </html>
  )
}
